### ISSUE TITLE
Implement utility functions- APIs

### ISSUE THREAD

**Issue by cleancoder1016** [WSUCEG-7140/minecraftclone#15]
Write code for utility functions or APIs modules for 3D vertices calculations, data manipulation, and other tasks such as directions using Pyglet, generating and rendering terrain such as hills, sand/rocks, trees, grass and water, rendering Skybox with moving clouds in the sky in the window, streamlined music to play, in main.py.  
Design and write program codes using python and pyglet for
- Terrain and clouds modules(Create coordinate vertices x. y and z for the perlin noise to generate terrain)
- Skybox modules(Create coordinate vertices for skys)
- Joystick and keybord modules (Process joystick and keyboard keys and mouse inputs)
- Common utility modules (Calculate coordinate transform for directions)
- main module (Set up the window, skybox, draw terrain and process user inputs)
- collider and controller modules (Colliding and controlling the user movements)

**Comment by kruslin2** [comment]
Utility functions:
Implement certain direction on screen that the user using certain keys pressed want to move.

**Comment by kruslin2** [comment]
Definition of done:
Each function module is automated unit tested and main.py module is also automated integration tested.

**Comment by kruslin2** [comment]
[Coverage for util.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftclone/files/11992424/Coverage.for.util.py_.100.pdf)
